# Generated by Django 5.0.4 on 2024-05-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
