# Generated by Django 5.0.4 on 2024-09-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
